### ISSUE TITLE
errorHandler inside auth srv is not connected

### ISSUE THREAD

**Issue by ghislaingenay** [ghislaingenay/redifood#6]
This code was extracted from a previous work and tutorial and was working properly. I just made a few changes which shoudn't break the layout from serializeErrors().
The proper statusCode is recover but not the message and a HTML is displayed instead.
`<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>Error: Username already in use<br> &nbsp; &nbsp;at /app/src/controllers/auth.controller.ts:16:11<br> &nbsp; &nbsp;at Generator.next (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at fulfilled (/app/src/controllers/auth.controller.ts:5:58)<br> &nbsp; &nbsp;at processTicksAndRejections (node:internal/process/task_queues:96:5)</pre>
</body>

</html>`

**Comment by ghislaingenay** [comment]
The error handling with node won't be implemented. So I used TypeScript to avoid writing too much hardcoded code.
